name: scroll_experiments
description: A new Flutter project.
version: 1.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.21.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  shaders:
    - shaders/motion_blur.frag
