name: motion_blur_scrollable
description: "Motion blur for scrollable widgets"
version: 1.0.0
repository: "https://github.com/1l0/motion_blur_scrollable"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  shaders:
    - assets/shaders/motion_blur.frag
